pure_pursuit:
  ros__parameters:
    trajectory_csv: "/home/car1/f1tenth_ws/src/darc_f1tenth_system/f1tenth_stack/racelines/struggle_screen_recording.csv"
    publish_rviz: True
    pp_steer_L_fast: 2.5
    pp_steer_L_slow: 1.25
    kp_fast: 0.35
    kp_slow: 0.5
    L_threshold_speed: 4.0
    odom_topic: "/pf/pose/odom"
    pp_current_goal_topic: "pp_current_goal_rviz"
    pp_spline_topic: "pp_spline_rviz"
    color_points_topic: "color_points_rviz"
    spline_index_topic: "car_spline_index"
    drive_topic: "drive"
    global_goal_topic: "global_goal_pure_pursuit"
    use_obs_avoid_topic: "use_obs_avoid"
    
